// Command generate pins the released kado-app Search Document v1 artifacts.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

const pinnedManifestSHA256 = "000f3f58ea4fcf2cc105e1f4904ea2d392df8088c79fa0cc0e7514436a7a2713"

type manifest struct {
	Contract      string                   `json:"contract"`
	Version       string                   `json:"version"`
	SchemaVersion string                   `json:"schema_version"`
	Artifacts     map[string]manifestEntry `json:"artifacts"`
	Fixtures      map[string]manifestEntry `json:"fixtures"`
}

type manifestEntry struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

func main() {
	source := os.Getenv("KADO_APP_SEARCH_CONTRACT")
	if source == "" {
		source = filepath.Clean("../../../kado-app/contracts/search-document/v1")
	}
	manifestBytes := mustRead(filepath.Join(source, "manifest.gen.json"))
	mustChecksum("manifest.gen.json", manifestBytes, pinnedManifestSHA256)

	var release manifest
	if err := json.Unmarshal(manifestBytes, &release); err != nil {
		panic(fmt.Errorf("decode authoritative manifest: %w", err))
	}
	if release.Contract != "kado.search-document" ||
		release.Version != "v1" ||
		release.SchemaVersion != "kado.search-document.v1" {
		panic("authoritative manifest does not describe Search Document v1")
	}

	assets := map[string][]byte{"manifest.gen.json": manifestBytes}
	for _, name := range []string{"schema", "context", "semantics"} {
		entry, ok := release.Artifacts[name]
		if !ok {
			panic("authoritative manifest is missing " + name)
		}
		assets[entry.Path] = checkedRead(source, entry)
	}
	for _, entry := range release.Fixtures {
		assets[entry.Path] = checkedRead(source, entry)
	}

	names := make([]string, 0, len(assets))
	for name := range assets {
		names = append(names, name)
	}
	sort.Strings(names)

	var generated bytes.Buffer
	generated.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	generated.WriteString("package searchcontract\n\n")
	generated.WriteString("var generatedCompressedAssets = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(
			&generated,
			"\t%s: %s,\n",
			strconv.Quote(name),
			strconv.Quote(compress(assets[name])),
		)
	}
	generated.WriteString("}\n")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated assets: %w", err))
	}
	if err := os.WriteFile("assets.gen.go", formatted, 0o644); err != nil {
		panic(fmt.Errorf("write generated assets: %w", err))
	}
}

func checkedRead(root string, entry manifestEntry) []byte {
	if entry.Path == "" ||
		filepath.IsAbs(entry.Path) ||
		filepath.Clean(entry.Path) != entry.Path ||
		entry.Path == ".." ||
		len(entry.Path) >= 3 && entry.Path[:3] == "../" {
		panic("authoritative manifest contains an unsafe artifact path")
	}
	value := mustRead(filepath.Join(root, entry.Path))
	mustChecksum(entry.Path, value, entry.SHA256)
	return value
}

func mustRead(path string) []byte {
	value, err := os.ReadFile(path)
	if err != nil {
		panic(fmt.Errorf("read %s: %w", path, err))
	}
	return value
}

func mustChecksum(name string, value []byte, expected string) {
	digest := sha256.Sum256(value)
	actual := hex.EncodeToString(digest[:])
	if actual != expected {
		panic(fmt.Errorf("%s checksum = %s, want %s", name, actual, expected))
	}
}

func compress(value []byte) string {
	var output bytes.Buffer
	writer := gzip.NewWriter(&output)
	if _, err := writer.Write(value); err != nil {
		panic(fmt.Errorf("compress generated asset: %w", err))
	}
	if err := writer.Close(); err != nil {
		panic(fmt.Errorf("close generated asset: %w", err))
	}
	return base64.StdEncoding.EncodeToString(output.Bytes())
}
