// Command generate pins the released kado-app Search Document v1 and v2 artifacts.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

var pinnedManifestSHA256 = map[string]string{
	"v1": "cb4344c5058880e95b41d6c6412b209fa8d16417e04d6eb5119d3771a3d9def9",
	"v2": "81a52f900de7cc3ffd6b42fa8b1742163fa0e63b6b40d0c7a94eada408a125f0",
}

type manifest struct {
	Contract      string                   `json:"contract"`
	Version       string                   `json:"version"`
	SchemaVersion string                   `json:"schema_version"`
	Artifacts     map[string]manifestEntry `json:"artifacts"`
	Fixtures      map[string]manifestEntry `json:"fixtures"`
}

type manifestEntry struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

func main() {
	sourceRoot := os.Getenv("KADO_APP_SEARCH_CONTRACT")
	if sourceRoot == "" {
		sourceRoot = filepath.Clean("../../../kado-app/contracts/search-document")
	}
	assets := map[string][]byte{}
	for _, version := range []string{"v1", "v2"} {
		source := filepath.Join(sourceRoot, version)
		manifestBytes := mustRead(filepath.Join(source, "manifest.gen.json"))
		mustChecksum(version+"/manifest.gen.json", manifestBytes, pinnedManifestSHA256[version])

		var release manifest
		if err := json.Unmarshal(manifestBytes, &release); err != nil {
			panic(fmt.Errorf("decode authoritative %s manifest: %w", version, err))
		}
		if release.Contract != "kado.search-document" ||
			release.Version != version ||
			release.SchemaVersion != "kado.search-document."+version {
			panic("authoritative manifest does not describe Search Document " + version)
		}

		assets[version+"/manifest.gen.json"] = manifestBytes
		for _, name := range []string{"schema", "context", "semantics"} {
			entry, ok := release.Artifacts[name]
			if !ok {
				panic("authoritative " + version + " manifest is missing " + name)
			}
			assets[version+"/"+entry.Path] = checkedRead(source, entry)
		}
		fixtureRoot := filepath.Join("testfixture", version)
		if err := os.MkdirAll(fixtureRoot, 0o755); err != nil {
			panic(fmt.Errorf("create %s fixture directory: %w", version, err))
		}
		for name, entry := range release.Fixtures {
			if name == "" || filepath.Base(name) != name {
				panic("authoritative manifest contains an unsafe fixture name")
			}
			if err := os.WriteFile(
				filepath.Join(fixtureRoot, name+".json"),
				checkedRead(source, entry),
				0o644,
			); err != nil {
				panic(fmt.Errorf("write %s fixture %s: %w", version, name, err))
			}
		}
	}

	names := make([]string, 0, len(assets))
	for name := range assets {
		names = append(names, name)
	}
	sort.Strings(names)

	var generated bytes.Buffer
	generated.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	generated.WriteString("package searchcontract\n\n")
	generated.WriteString("var generatedCompressedAssets = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(
			&generated,
			"\t%s: %s,\n",
			strconv.Quote(name),
			strconv.Quote(compress(assets[name])),
		)
	}
	generated.WriteString("}\n")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated assets: %w", err))
	}
	if err := os.WriteFile("assets.gen.go", formatted, 0o644); err != nil {
		panic(fmt.Errorf("write generated assets: %w", err))
	}
}

func checkedRead(root string, entry manifestEntry) []byte {
	if entry.Path == "" ||
		path.IsAbs(entry.Path) ||
		path.Clean(entry.Path) != entry.Path ||
		strings.Contains(entry.Path, "\\") ||
		entry.Path == ".." ||
		len(entry.Path) >= 3 && entry.Path[:3] == "../" {
		panic("authoritative manifest contains an unsafe artifact path")
	}
	value := mustRead(filepath.Join(root, filepath.FromSlash(entry.Path)))
	value = bytes.ReplaceAll(value, []byte("\r\n"), []byte("\n"))
	mustChecksum(entry.Path, value, entry.SHA256)
	return value
}

func mustRead(path string) []byte {
	value, err := os.ReadFile(path)
	if err != nil {
		panic(fmt.Errorf("read %s: %w", path, err))
	}
	return value
}

func mustChecksum(name string, value []byte, expected string) {
	digest := sha256.Sum256(value)
	actual := hex.EncodeToString(digest[:])
	if actual != expected {
		panic(fmt.Errorf("%s checksum = %s, want %s", name, actual, expected))
	}
}

func compress(value []byte) string {
	var output bytes.Buffer
	writer := gzip.NewWriter(&output)
	if _, err := writer.Write(value); err != nil {
		panic(fmt.Errorf("compress generated asset: %w", err))
	}
	if err := writer.Close(); err != nil {
		panic(fmt.Errorf("close generated asset: %w", err))
	}
	return base64.StdEncoding.EncodeToString(output.Bytes())
}
