// Package searchcontract validates and projects the released Search Document.
//
// The runtime assets are generated byte-for-byte from kado-app's authoritative
// released v1 manifest, schema, context, semantics, and fixtures.
package searchcontract

//go:generate go run ./cmd/generate
